apiVersion: kubeadm.k8s.io/v1beta2 
kind: ClusterConfiguration 
kubernetesVersion: v1.18.2 
imageRepository: registry.cn-hangzhou.aliyuncs.com/google_containers 
controlPlaneEndpoint: "k8s.master:6443" 
networking:   
  serviceSubnet: "10.96.0.0/16"   
  podSubnet: "172.18.0.1/16"   
  dnsDomain: "cluster.local" 
